<?php
/**
 * Regulatory knowledge base: what each regulator actually is, what its
 * licence does and doesn't guarantee, and what its compensation scheme
 * actually covers. Every figure here (compensation amounts, register
 * URLs) matches exactly what globalfxhub_broker_verify_links() and
 * globalfxhub_broker_investor_protection() already use per-broker, so
 * this knowledge base and every individual review page stay consistent
 * with each other by construction rather than by manual upkeep.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

function globalfxhub_get_regulation_pages() {
    return array(
        'cysec' => array(
            'title'   => 'CySEC: Cyprus Securities and Exchange Commission',
            'summary' => 'Cyprus\'s financial regulator, and the licence most EU-facing forex/CFD brokers on this site hold -- it carries full EU/MiFID passporting rights and a real investor-compensation fund.',
            'content' => '<p>CySEC (the Cyprus Securities and Exchange Commission) licenses and supervises Cyprus Investment Firms (CIFs), which is why so many forex and CFD brokers serving EU clients are licensed there: a single CySEC licence lets a firm passport its services across the entire EU/EEA under MiFID II, without needing a separate licence in every member state.</p><h2>What a CySEC licence actually requires</h2><p>A CIF must meet minimum capital requirements, segregate client funds from the firm\'s own operating funds, follow EU-wide leverage caps for retail clients under ESMA\'s product intervention rules (typically 30:1 on major currency pairs, down to 2:1 on crypto CFDs), and submit to CySEC\'s ongoing supervision and periodic inspections.</p><h2>Investor compensation: the Investor Compensation Fund (ICF)</h2><p>If a CySEC-licensed firm fails and can\'t return client assets, the Investor Compensation Fund covers eligible retail clients up to &euro;20,000 per person. This is a real statutory scheme, not marketing language -- but it has a cap, it applies per person (not per account), and it only applies to the specific CySEC-licensed entity, not to an unrelated offshore sister brand that happens to share a brand name.</p><h2>What CySEC licensing does NOT guarantee</h2><p>A CySEC licence is a real, meaningful form of oversight, but it isn\'t a guarantee a broker is a good one to trade with, and it isn\'t a guarantee of profitability or even of good execution quality. CySEC has fined numerous licensed firms for misconduct -- see our <a href="' . home_url( '/news/brokers/' ) . '">Broker News</a> for specific, dated examples -- and a licence can be voluntarily surrendered or formally withdrawn, after which the firm is no longer EU-regulated even if its marketing hasn\'t caught up. Always check the register directly rather than trusting a broker\'s own claim.</p><h2>How to verify a CySEC licence yourself</h2><p>Search the firm\'s exact legal entity name (not just its brand name) on the <a href="https://www.cysec.gov.cy/en-GB/entities/investment-firms/cypriot/" target="_blank" rel="noopener">official CySEC register of Cypriot Investment Firms</a>, and confirm the licence number matches what the broker discloses. Every CySEC-regulated broker reviewed on this site has a direct link to this register on its own review page.</p><h2>CySEC-regulated brokers on this site</h2><p>See our full, ranked list of <a href="' . home_url( '/best/cysec-regulated/' ) . '">CySEC-regulated brokers</a>, sorted by our disclosed overall score.</p>',
        ),
        'fca' => array(
            'title'   => 'FCA: UK Financial Conduct Authority',
            'summary' => 'The UK\'s financial regulator. An FCA licence carries FSCS compensation cover and some of the strictest retail-conduct rules of any regulator covered on this site.',
            'content' => '<p>The Financial Conduct Authority regulates financial services firms operating in the UK, including forex and CFD brokers. Since Brexit, an FCA licence covers only UK clients directly -- it no longer carries automatic EU passporting, so a group with both FCA and CySEC entities is typically running two separately-licensed, separately-capitalized businesses, not one licence covering both regions.</p><h2>What an FCA licence actually requires</h2><p>FCA-regulated firms must meet capital adequacy requirements, segregate client money, follow the same ESMA-style retail leverage caps the UK retained after Brexit, and comply with the FCA\'s Consumer Duty rules, which require firms to act to deliver good outcomes for retail customers -- not just avoid actively harming them.</p><h2>Investor compensation: the Financial Services Compensation Scheme (FSCS)</h2><p>If an FCA-authorised firm fails, eligible retail clients are covered by the FSCS up to &pound;85,000 per person. Like the CySEC ICF, this is a real statutory scheme with a hard cap, and it applies only to the specific FCA-authorised entity -- not to an offshore sister brand using the same name.</p><h2>What FCA licensing does NOT guarantee</h2><p>The FCA has fined and censured FCA-authorised firms, including some reviewed on this site -- see our <a href="' . home_url( '/news/brokers/' ) . '">Broker News</a> for specific, dated examples (unfair customer treatment, improper client reclassification, and others). The FCA also publishes public warnings about clone firms that impersonate genuinely-authorised brokers using near-identical names or domains -- always confirm you\'re dealing with the exact authorised entity, not a lookalike.</p><h2>How to verify an FCA licence yourself</h2><p>Search the firm\'s exact legal entity name and Firm Reference Number (FRN) on the <a href="https://register.fca.org.uk/s/" target="_blank" rel="noopener">official FCA Financial Services Register</a>. The register also lists any current warnings against clone firms using a similar name.</p><h2>FCA-regulated brokers on this site</h2><p>See our full, ranked list of <a href="' . home_url( '/best/fca-regulated/' ) . '">FCA-regulated brokers</a>, sorted by our disclosed overall score.</p>',
        ),
        'seychelles-fsa' => array(
            'title'   => 'Seychelles FSA: Financial Services Authority',
            'summary' => 'An offshore regulator many brokers use for clients outside the EU/UK. Real licensing, but materially lighter oversight and no statutory investor-compensation scheme.',
            'content' => '<p>The Seychelles Financial Services Authority licenses Securities Dealers, including many forex/CFD brokers serving clients outside the EU and UK. It is a real regulator -- a Seychelles FSA licence is not the same as being entirely unregulated -- but its capital requirements, conduct rules, and supervisory intensity are materially lighter than CySEC\'s or the FCA\'s.</p><h2>What a Seychelles FSA licence requires</h2><p>Licensed Securities Dealers must meet the FSA\'s (lower) minimum capital requirements and maintain basic record-keeping and reporting obligations, but retail leverage caps and conduct-of-business rules are far less prescriptive than under MiFID or FCA rules -- which is part of why offshore entities can advertise much higher leverage than their EU/UK sister brands.</p><h2>Investor compensation: there isn\'t one</h2><p>This is the single most important difference from CySEC or the FCA: the Seychelles FSA does not operate a statutory investor-compensation scheme. If a Seychelles-licensed firm fails, there is no equivalent to the EU\'s &euro;20,000 ICF cover or the UK\'s &pound;85,000 FSCS cover. Whatever protection exists is whatever the firm itself can actually pay out -- which is also why many brokers on this site hold a Seychelles licence as a secondary, offshore-client-facing entity alongside a Tier-1 EU/UK one, rather than as their only regulatory credential.</p><h2>What to watch for</h2><p>Offshore licensing is also where this site\'s research has found the highest concentration of serious red flags -- regulator blacklistings, false regulatory claims, and clone/impersonation risk are all more common among Seychelles-only (and other pure-offshore) brokers than among CySEC- or FCA-regulated ones. See our <a href="' . home_url( '/news/brokers/' ) . '">Broker News</a> for specific, dated examples, and treat a Seychelles-only regulatory footprint as a real factor in a broker\'s risk profile, not a formality to skim past.</p><h2>How to verify a Seychelles FSA licence yourself</h2><p>Check the firm\'s exact legal entity name against the <a href="https://fsaseychelles.sc/" target="_blank" rel="noopener">official FSA Seychelles register</a>. Entity-name mismatches between what a broker markets and what\'s actually on the register are common enough in this research to always check directly rather than trusting a broker\'s own citation of its licence number.</p>',
        ),
        'investor-compensation-schemes-explained' => array(
            'title'   => 'Investor Compensation Schemes Explained',
            'summary' => 'What actually happens to your money if a regulated broker fails -- and why the answer depends entirely on which specific entity and regulator you\'re actually dealing with.',
            'content' => '<p>"Regulated" doesn\'t automatically mean "your money is protected if the firm fails" -- what protection exists, and how much, depends entirely on which specific regulator licenses the exact entity you\'ve signed up with.</p><h2>EU/CySEC: the Investor Compensation Fund (ICF)</h2><p>Up to &euro;20,000 per eligible retail client if a CySEC-licensed Cyprus Investment Firm fails. See our <a href="' . home_url( '/regulation/cysec/' ) . '">CySEC page</a> for detail.</p><h2>UK/FCA: the Financial Services Compensation Scheme (FSCS)</h2><p>Up to &pound;85,000 per eligible retail client if an FCA-authorised firm fails. See our <a href="' . home_url( '/regulation/fca/' ) . '">FCA page</a> for detail.</p><h2>Offshore regulators (Seychelles FSA and similar)</h2><p>Typically no statutory compensation scheme at all. See our <a href="' . home_url( '/regulation/seychelles-fsa/' ) . '">Seychelles FSA page</a> for detail.</p><h2>The part that actually trips people up</h2><p>Many brokers operate multiple legal entities under one brand -- a CySEC-regulated EU entity and a Seychelles-regulated offshore entity, say -- each with its own separate client base and its own separate (or absent) compensation cover. Signing up through the wrong regional website, or being onboarded into the offshore entity because you\'re outside the EU/UK, can mean the compensation scheme you assumed applied to you simply doesn\'t. Always confirm, in writing from the broker, exactly which legal entity your account is held with, and check that entity\'s specific licence -- not just the brand\'s general regulatory reputation -- against the relevant register.</p>',
        ),
        'how-to-verify-a-broker-license' => array(
            'title'   => 'How to Verify a Broker\'s Licence Yourself',
            'summary' => 'A broker citing a licence number proves nothing on its own -- here\'s how to actually check it against the regulator\'s own public register in a couple of minutes.',
            'content' => '<p>Any website can print a licence number. The only way to know it\'s real, current, and actually belongs to the entity you\'re dealing with is to check the regulator\'s own public register directly -- never rely on the broker\'s own citation of its own status.</p><h2>Step 1: get the exact legal entity name</h2><p>Not the brand name -- the legal entity. "IG" the brand, for instance, operates through specifically-named legal entities like IGM Forex Ltd. This is usually in the broker\'s terms of service, a legal/impressum page, or account-opening documents.</p><h2>Step 2: search the regulator\'s own register, not a search engine</h2><p>Go directly to the regulator\'s own site: <a href="https://www.cysec.gov.cy/en-GB/entities/investment-firms/cypriot/" target="_blank" rel="noopener">CySEC\'s register</a>, the <a href="https://register.fca.org.uk/s/" target="_blank" rel="noopener">FCA\'s register</a>, or the <a href="https://fsaseychelles.sc/" target="_blank" rel="noopener">FSA Seychelles register</a>, depending on which regulator the broker claims. A third-party "verification" site is not the same thing as the primary source.</p><h2>Step 3: confirm the licence number AND the entity name both match</h2><p>A licence number alone isn\'t enough -- confirm the register lists that exact number against that exact legal entity name. This site\'s own research has repeatedly found cases where a licence number is real but belongs to a different entity than the one marketing it, or where the register lists a different legal name than the one a broker advertises.</p><h2>Step 4: check the licence status, not just its existence</h2><p>A register entry can show a licence that\'s active, suspended, under examination for voluntary renunciation, or withdrawn entirely. "This firm has a licence number" and "this firm is currently authorised" are different questions -- check which one the register is actually telling you.</p><h2>Step 5: watch for clone/impersonation warnings</h2><p>Regulators including the FCA publish specific warnings about clone firms using a genuinely-authorised firm\'s name, logo, or a near-identical domain. If the regulator\'s own register or warning list mentions a clone for the firm you\'re checking, that\'s directly relevant -- read it before depositing anything.</p>',
        ),
    );
}
